/**
 * Initial category taxonomy (see docs/CLASSIFICATION.md).
 * Categories are DB records: `keywords` feed the deterministic rule pass,
 * `prototype` is filled by `seed-categories` after embeddings are available.
 */

export interface CategorySeed {
  slug: string;
  name: string;
  description: string;
  keywords: string[];
}

export const CATEGORY_SEEDS: CategorySeed[] = [
  {
    slug: 'design-system',
    name: 'Design System',
    description: 'Tokens, colors, typography, shadows and visual components.',
    keywords: [
      'design system',
      'design-system',
      'tokens',
      'cores',
      'color palette',
      'tipografia',
      'typography',
      'sombras',
      'shadows',
      'neo-brutalism',
      'visual component',
      'grid',
      'layout',
    ],
  },
  {
    slug: 'architecture',
    name: 'Arquitetura',
    description: 'Structure, modules, flows and technical architecture decisions.',
    keywords: [
      'arquitetura',
      'architecture',
      'modulo',
      'module',
      'camada',
      'layer',
      'fluxo',
      'flow',
      'clean architecture',
      'hexagonal',
      'monorepo',
      'workspace',
      'dependency injection',
      'dependencia',
      'data flow',
    ],
  },
  {
    slug: 'api',
    name: 'API',
    description: 'REST endpoints, contracts, rate limits.',
    keywords: [
      'api',
      'endpoint',
      'rest',
      'http',
      'contract',
      'rate limit',
      'rota',
      'route',
      'swagger',
      'openapi',
      'request',
      'response',
    ],
  },
  {
    slug: 'database',
    name: 'Banco de Dados',
    description: 'Schema, indexes, migrations and search.',
    keywords: [
      'banco de dados',
      'database',
      'postgres',
      'postgresql',
      'sql',
      'prisma',
      'schema',
      'migracao',
      'migration',
      'indice',
      'index',
      'query',
      'pgvector',
      'redis',
      'model',
      'tabela',
      'table',
      'hnsv',
      'hnsw',
    ],
  },
  {
    slug: 'security',
    name: 'Segurança',
    description: 'OWASP, rate limiting, auth, LGPD.',
    keywords: [
      'seguranca',
      'security',
      'owasp',
      'lgpd',
      'sql injection',
      'xss',
      'csrf',
      'autenticacao',
      'authentication',
      'senha',
      'password',
      'criptografia',
      'encryption',
      'jwt',
      'secret',
      'vulnerabilidade',
      'vulnerability',
      'rate limiting',
      'api key',
    ],
  },
  {
    slug: 'deployment',
    name: 'Deploy & Infra',
    description: 'Docker, CI/CD, nginx, observability.',
    keywords: [
      'deploy',
      'deployment',
      'docker',
      'dockerfile',
      'ci',
      'cd',
      'github actions',
      'nginx',
      'observabilidade',
      'observability',
      'infra',
      'infrastructure',
      'vercel',
      'container',
      'pipeline',
      'monitoramento',
      'monitoring',
    ],
  },
  {
    slug: 'testing',
    name: 'Testes',
    description: 'Strategy, coverage, E2E, best practices.',
    keywords: [
      'teste',
      'testes',
      'test',
      'jest',
      'vitest',
      'playwright',
      'cobertura',
      'coverage',
      'e2e',
      'unit',
      'mock',
      'spec',
      'tdd',
      'integration test',
      'teste de integracao',
    ],
  },
  {
    slug: 'mcp',
    name: 'MCP',
    description: 'MCP servers/tools, agent integrations.',
    keywords: [
      'mcp',
      'model context protocol',
      'tool',
      'tools',
      'stdio',
      'streamable http',
      'agente',
      'agent',
      'handshake',
    ],
  },
  {
    slug: 'prompt',
    name: 'Prompts',
    description: 'Prompt library, prompt engineering.',
    keywords: [
      'prompt',
      'prompts',
      'engenharia de prompt',
      'meta-prompt',
      'auditoria',
      'refatoracao',
      'instrucoes',
      'copy',
      'llm prompt',
    ],
  },
  {
    slug: 'tutorial',
    name: 'Tutoriais & Guias',
    description: 'Usage guides, step-by-step, tutorials.',
    keywords: [
      'tutorial',
      'tutoriais',
      'guia',
      'guide',
      'passo a passo',
      'step-by-step',
      'how-to',
      'como usar',
      'walkthrough',
      'manual',
    ],
  },
  {
    slug: 'seo',
    name: 'SEO',
    description: 'Metadata, sitemap, structured data.',
    keywords: [
      'seo',
      'sitemap',
      'json-ld',
      'structured data',
      'meta tags',
      'canonical',
      'robots',
      'page speed',
      'lighthouse',
      'serp',
      'google',
      'indexacao',
      'indexação',
      'core web vitals',
      'og image',
    ],
  },
  {
    slug: 'workflow',
    name: 'Convenções & Workflow',
    description: 'Gates, code patterns, process, CLAUDE/AGENTS.',
    keywords: [
      'workflow',
      'convencao',
      'convenções',
      'conventions',
      'gate',
      'padrao',
      'padrão',
      'pattern',
      'claude.md',
      'agents.md',
      'processo',
      'process',
      'qualidade',
      'quality',
      'commit',
      'code review',
    ],
  },
  {
    slug: 'decision',
    name: 'Decisões (ADR)',
    description: 'ADRs, previous decisions, roadmap.',
    keywords: [
      'adr',
      'decision',
      'decisao',
      'decisão',
      'roadmap',
      'registro de decisoes',
      'decision record',
    ],
  },
  {
    slug: 'pwa',
    name: 'PWA',
    description: 'Manifest, service worker, offline.',
    keywords: [
      'pwa',
      'manifest',
      'service worker',
      'offline',
      'instalavel',
      'installable',
      'web app',
      'cache api',
    ],
  },
  {
    slug: 'data',
    name: 'Dados & Domínio',
    description: 'Dictionaries, catalogs, business rules.',
    keywords: [
      'dados',
      'data',
      'dicionario',
      'dictionary',
      'catalogo',
      'catalog',
      'regras de negocio',
      'business rules',
      'dominio',
      'domain',
      'anvisa',
      'medicamentos',
      'vagas',
      'jobs',
    ],
  },
  {
    slug: 'general',
    name: 'Geral',
    description: 'Fallback when no category reaches confidence.',
    keywords: [],
  },
];
